@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml
actor user
user -> DietSession : input
activate DietSession

DietSession -> CommandLib : get()
activate CommandLib
CommandLib --> DietSession : FoodItemHelp
deactivate CommandLib

DietSession -> FoodItemHelp : execute()
activate FoodItemHelp

FoodItemHelp --> DietSession
deactivate FoodItemHelp

DietSession --> user : output
@enduml