@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml
actor user
user -> DietSession : input
activate DietSession

DietSession -> CommandLib : get()
activate CommandLib
CommandLib --> DietSession : FoodItemClear
deactivate CommandLib

DietSession -> FoodItemClear : execute()
activate FoodItemClear

FoodItemClear --> DietSession
deactivate FoodItemClear

DietSession --> user : output
@enduml