@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml

actor user
activate DietSession
user -> Ui++ : Add FoodItem Command
Ui --> DietSession -- : input

ref over DietSession, DietSessionParser, CommandLib: parse user input in Diet Session Menu

DietSession -> Command ++ : execute(foodList)
Command -> Food **
activate Food
Food --> Command -- : new Food Item
Command -> DietSession: foodList.add(new Food Item)
DietSession --> Command
deactivate Food
Command --> DietSession --

deactivate Command

DietSession -> CommandResult ++ : getFeedbackMessage(result)
CommandResult --> DietSession -- : message
DietSession -> Ui ++ : showToUser(message)
destroy CommandResult
Ui --> user
destroy Command
deactivate Ui

@enduml
