@startuml
!include ../../umldiagram/style.puml
actor user
user -> WorkoutManager : input
activate WorkoutManager

WorkoutManager -> CommandLib : get()
activate CommandLib
CommandLib --> WorkoutManager : Command
deactivate CommandLib

WorkoutManager -> ListCommand : execute()
activate ListCommand

ListCommand -> PastRecordList : list()
activate PastRecordList
PastRecordList -> WorkoutManagerParser: listCommandParse()
activate WorkoutManagerParser
WorkoutManagerParser --> PastRecordList: ConditionList
deactivate WorkoutManagerParser
PastRecordList --> ListCommand : formated list
deactivate PastRecordList

ListCommand --> WorkoutManager : CommandResult
deactivate ListCommand

WorkoutManager ->  user : output

@enduml