@startuml
actor user
activate WorkoutManager
user -> WorkoutManager
WorkoutManager -> WorkoutManagerParser : parse()
activate WorkoutManagerParser
WorkoutManagerParser -> WorkoutManager : parsed input
deactivate WorkoutManagerParser

WorkoutManager -> Command : execute()
activate Command

Command -> PastRecordList : add()
activate PastRecordList

PastRecordList -> WorkoutManagerStorage : add()
activate WorkoutManagerStorage
WorkoutManagerStorage --> PastRecordList : filePath
deactivate WorkoutManagerStorage

PastRecordList --> Command : filePath
deactivate PastRecordList

Command -> Command : new WorkoutSession
Command -> workoutSession : start()
activate workoutSession
workoutSession -> Command
deactivate workoutSession

Command -> WorkoutManager : CommandResult
deactivate Command

WorkoutManager ->  user : output

@enduml