@startuml
!include ../../umldiagram/style.puml

rectangle "Parser"{
rectangle "XYZCommandParser"
}

rectangle "CommandLib"

rectangle "Commands"{
rectangle "Command"
rectangle "XYZCommand"
}
rectangle "CommandResult"

XYZCommandParser ..> CommandLib
CommandLib ..> XYZCommand: executes
XYZCommand -right-|> Command
Command .up.> CommandResult: creates
@enduml