@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
activate ProfileSession
user -> Ui++ : add
Ui --> ProfileSession -- : input

ProfileSession -> ProfileParser ++ : parseCommand(input)
ProfileParser --> ProfileSession -- : parsedInput

ProfileSession -> CommandLib ++ : getCommand(parsedInput)
CommandLib --> ProfileSession -- : command

ProfileSession -> Command ++ : execute()
Command -> ProfileStorage ++ : loadData()
ProfileStorage --> Command -- : profile

alt hasExistingProfile
    Command --> ProfileSession : result
else else
    Command -> ProfileParser ++ : extractCommandTagAndInfo(parsedInput)
    ProfileParser --> Command -- : parsedInfo
    Command -> Profile ** : parsedInfo
    activate Profile
    Profile --> Command -- : newProfile
    Command -> ProfileStorage ++ : saveData(newProfile)
    destroy Profile
    ProfileStorage --> Command --
    Command --> ProfileSession -- : result
end

deactivate Command
destroy Command

ProfileSession -> CommandResult ++ : getFeedbackMessage(result)
CommandResult --> ProfileSession -- : message
ProfileSession -> Ui ++ : showToUser(message)
destroy CommandResult
Ui --> user
deactivate Ui
@enduml
