@startuml
!include ../../umldiagram/style.puml

actor user
activate ProfileSession
user -> CommonUi++ : Delete Profile Command
CommonUi --> ProfileSession -- : input

ref over ProfileSession, ProfileParser, CommandLib: parse user input in ProfileSession

ProfileSession -> Command ++ : execute()
Command -> ProfileStorage ++ : loadData()
ProfileStorage --> Command -- : profile

alt hasExistingProfile
    Command -> CommonUi ++ : getConfirmation()
    CommonUi --> Command -- : isConfirmed

    alt isConfirmed
        Command -> ProfileStorage ++ : saveData(null)
        ProfileStorage --> Command --
        Command --> ProfileSession: result
    else else
        Command --> ProfileSession: result
    end
else else
    Command --> ProfileSession -- : result
end

deactivate Command
destroy Command

ref over user, ProfileSession, CommonUi: show message to user in ProfileSession

@enduml
