@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
activate ProfileSession
user -> Ui++ : Delete Profile Command
Ui --> ProfileSession -- : input

ref over ProfileSession, ProfileParser, CommandLib: parse user input in Profile Menu

ProfileSession -> Command ++ : execute()
Command -> ProfileStorage ++ : loadData()
ProfileStorage --> Command -- : profile

alt hasExistingProfile
    Command -> Ui ++ : getConfirmation()
    Ui --> Command -- : isConfirmed

    alt isConfirmed
        Command -> ProfileStorage ++ : saveData(null)
        ProfileStorage --> Command --
        Command --> ProfileSession: result
    else else
        Command --> ProfileSession: result
    end
else else
    Command --> ProfileSession -- : result
end

deactivate Command
destroy Command

ProfileSession -> CommandResult ++ : getFeedbackMessage(result)
CommandResult --> ProfileSession -- : message
ProfileSession -> Ui ++ : showToUser(message)
destroy CommandResult
Ui --> user
deactivate Ui
@enduml
