@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

mainframe <b>sd</b> parse user input in ProfileSession

    ProfileSession -> ProfileParser ++ : parseCommand(input)
    ProfileParser --> ProfileSession -- : parsedInput

    ProfileSession -> CommandLib ++ : getCommand(parsedInput)
    CommandLib --> ProfileSession -- : command

@enduml
