@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml

mainframe <b>sd</b> parse user input in ProfileSession
    actor user
    ProfileSession -> CommandResult ++ : getFeedbackMessage(result)
    CommandResult --> ProfileSession -- : message
    ProfileSession -> Ui ++ : showToUser(message)
    destroy CommandResult
    Ui --> user
    deactivate Ui

@enduml
