@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
activate ProfileSession
user -> Ui++ : view
Ui --> ProfileSession : input

ProfileSession -> ProfileParser ++ : parseCommand(input)
ProfileParser --> ProfileSession -- : parsedInput

ProfileSession -> CommandLib ++ : getCommand(parsedInput)
CommandLib --> ProfileSession -- : command

ProfileSession -> Command ++ : execute()
Command -> ProfileStorage ++ : loadData()
ProfileStorage --> Command -- : profile

opt hasExistingProfile
    Command -> Profile : toString()
    activate Profile
    Profile --> Command -- : profileString
    destroy Profile
    Command --> ProfileSession : result
else
    Command --> ProfileSession --: result
end

deactivate Command
destroy Command

ProfileSession -> CommandResult ++ : getFeedbackMessage(result)
CommandResult --> ProfileSession -- : message
ProfileSession -> Ui : showToUser(message)
destroy CommandResult
Ui --> user
deactivate Ui
@enduml
