@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
activate ProfileSession
user -> Ui++ : View Profile Command
Ui --> ProfileSession -- : input

ref over ProfileSession, ProfileParser, CommandLib: parse user input in Profile Menu

ProfileSession -> Command ++ : execute()
Command -> ProfileStorage ++ : loadData()
ProfileStorage --> Command -- : profile

alt hasExistingProfile
    Command -> DietManager**
    activate DietManager
    DietManager --> Command --
    Command -> DietManager ++ : getTodayTotalCalories()
    DietManager --> Command -- : calories
    Command --> ProfileSession : result
    destroy DietManager
else else
    Command --> ProfileSession --: result
end

deactivate Command
destroy Command

ProfileSession -> CommandResult ++ : getFeedbackMessage(result)
CommandResult --> ProfileSession -- : message
ProfileSession -> Ui ++ : showToUser(message)
destroy CommandResult
Ui --> user
deactivate Ui
@enduml
