@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml

actor user
user -> DietManager : "List"
activate DietManager
DietManager -> DietManagerParser : parse(userInput)
activate DietManagerParser
DietManagerParser --> DietManager : commParts[]
deactivate DietManagerParser
DietManager -> CommandLib : getCommand(commParts[0])
activate CommandLib
CommandLib --> DietManager : command
deactivate CommandLib

DietManager -> DietSessionList : execute()
activate DietSessionList
    DietSessionList -> DietSessionList : formatList()
    activate DietSessionList
        DietSessionList -> DietSessionList : formatRow()
        activate DietSessionList
        DietSessionList --> DietSessionList
        deactivate DietSessionList
    DietSessionList --> DietSessionList
    deactivate DietSessionList
DietSessionList --> DietManager
deactivate DietSessionList
DietManager -> DietManagerUi : showToUser(message)
destroy DietSessionList
activate DietManagerUi
DietManagerUi --> user : output
deactivate DietManagerUi
@enduml