@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml
actor user
user -> DietManager : input
activate DietManager

DietManager -> CommandLib : get()
activate CommandLib
CommandLib --> DietManager : Command
deactivate CommandLib

DietManager -> DietSessionEdit ** : execute()
activate DietSessionEdit

DietSessionEdit -> DietStorage : readDietSession()
activate DietStorage
DietStorage --> DietSessionEdit : DietSession

DietSessionEdit -> DietSession ** : start()
activate DietSession
DietSession --> DietSessionEdit
deactivate DietSession
DietSessionEdit -> DietStorage : writeToStorageDietSession()
DietStorage --> DietSessionEdit
deactivate DietStorage
DietSessionEdit --> DietManager
deactivate DietSessionEdit

DietManager --> user : output
@enduml