@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml

actor user
user -> DietManager : "clear"
activate DietManager
DietManager -> DietManagerParser : parse(userInput)
activate DietManagerParser
DietManagerParser --> DietManager : commParts[]
deactivate DietManagerParser
DietManager -> CommandLib : getCommand(commParts[0])
activate CommandLib
CommandLib --> DietManager : command
deactivate CommandLib

DietManager -> DietSessionClear : execute()
activate DietSessionClear
alt checkConfirmation checkConfirmation(DIET_MENU_NAME, CLEAR_RECORD)
DietSessionClear -> DietSessionClear : deleteAllFiles()
activate DietSessionClear
DietSessionClear --> DietSessionClear
deactivate DietSessionClear
DietSessionClear --> DietManager : commandResult
else else
DietSessionClear --> DietManager : commandResult
end

deactivate DietSessionClear
destroy DietSessionClear
DietManager -> DietManagerUi : showToUser(message)
activate DietManagerUi
DietManagerUi --> user : output
deactivate DietManagerUi
@enduml
