@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include ../../umldiagram/style.puml

actor user
user -> DietManager : "delete [INDEX]"
activate DietManager
DietManager -> DietManagerParser : parse(userInput)
activate DietManagerParser
DietManagerParser --> DietManager : commParts[]
deactivate DietManagerParser
DietManager -> CommandLib : getCommand(commParts[0])
activate CommandLib
CommandLib --> DietManager : command
deactivate CommandLib

DietManager -> DietSessionDelete : execute()
activate DietSessionDelete

DietSessionDelete --> DietManager : result
deactivate DietSessionDelete
destroy DietSessionDelete

DietManager -> DietManagerUi : showToUser(message)
activate DietManagerUi
DietManagerUi --> user : output
deactivate DietManagerUi
@enduml
