@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
user -> WorkoutSession : add
activate WorkoutSession

WorkoutSession -> CommandLib : get()
activate CommandLib
CommandLib --> WorkoutSession : Command
deactivate CommandLib

WorkoutSession -> WorkoutSessionHelp : execute()
activate WorkoutSessionHelp
participant WorkoutSessionUi << Class >>
WorkoutSessionHelp -> WorkoutSessionUi : printHelp()
activate WorkoutSessionUi
WorkoutSessionUi --> WorkoutSessionHelp
deactivate WorkoutSessionUi

WorkoutSessionHelp --> WorkoutSession
deactivate WorkoutSessionHelp
@enduml