@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
user -> WorkoutSession : add
activate WorkoutSession

WorkoutSession -> CommandLib : get()
activate CommandLib
CommandLib --> WorkoutSession : Command
deactivate CommandLib

WorkoutSession -> WorkoutSessionSearch : execute()
activate WorkoutSessionSearch

opt searchTerm.length() > 0
    WorkoutSessionSearch -> WorkoutSessionSearch : formatList()
    activate WorkoutSessionSearch
    WorkoutSessionSearch --> WorkoutSessionSearch
    deactivate WorkoutSessionSearch
    opt SearchResult is not Empty
        participant CommonUi << Class >>
        WorkoutSessionSearch -> CommonUi : showToUser()
        activate CommonUi
        CommonUi --> WorkoutSessionSearch
        deactivate CommonUi
    else
        participant WorkoutSessionUi << Class >>
        WorkoutSessionSearch -> WorkoutSessionUi : searchResultsEmpty()
        activate WorkoutSessionUi
        WorkoutSessionUi --> WorkoutSessionSearch
        deactivate WorkoutSessionUi
    end
else
    participant WorkoutSessionUi << Class >>
    WorkoutSessionSearch -> WorkoutSessionUi : searchInputError()
    activate WorkoutSessionUi
    WorkoutSessionUi --> WorkoutSessionSearch
    deactivate WorkoutSessionUi
end

WorkoutSessionSearch-> WorkoutSession : exerciseList.add()
WorkoutSession --> WorkoutSessionSearch
WorkoutSessionSearch -> WorkoutSession.Storage : writeToStorage()
activate WorkoutSession.Storage
WorkoutSession.Storage --> WorkoutSessionSearch
deactivate WorkoutSession.Storage

WorkoutSessionSearch --> WorkoutSession
deactivate WorkoutSessionSearch
@enduml