@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
user -> Ui++ : Delete
Ui --> WorkoutSession -- : input

activate WorkoutSession

ref over WorkoutSession, WorkoutSessionParser, CommandLib: parse user input in WorkoutSession



WorkoutSession -> WorkoutSessionDelete : execute()
activate WorkoutSessionDelete

WorkoutSessionDelete-> WorkoutSession : exerciseList.remove()
WorkoutSession --> WorkoutSessionDelete
WorkoutSessionDelete -> WorkoutSessionStorage : writeToStorage()
activate WorkoutSessionStorage
WorkoutSessionStorage --> WorkoutSessionDelete
deactivate WorkoutSessionStorage

WorkoutSessionDelete --> WorkoutSession : result
deactivate WorkoutSessionDelete

ref over WorkoutSession, Ui, user: show message to user in WorkoutSession
@enduml