@startuml
!define PLANTUML_HOME %dirpath()/../../umldiagram
!include PLANTUML_HOME/style.puml

actor user
user -> Ui++ : Add
Ui --> WorkoutSession -- : input

activate WorkoutSession

ref over WorkoutSession, WorkoutSessionParser, CommandLib: parse user input in WorkoutSession

WorkoutSession -> CommandLib : get()
activate CommandLib
CommandLib --> WorkoutSession : Command
deactivate CommandLib

WorkoutSession -> WorkoutSessionAdd : execute()
activate WorkoutSessionAdd
WorkoutSessionAdd-> WorkoutSession : exerciseList.add()
WorkoutSession --> WorkoutSessionAdd
WorkoutSessionAdd -> WorkoutSession.Storage : writeToStorage()
activate WorkoutSession.Storage
WorkoutSession.Storage --> WorkoutSessionAdd
deactivate WorkoutSession.Storage

WorkoutSessionAdd --> WorkoutSession : result
deactivate WorkoutSessionAdd

ref over WorkoutSession, Ui, user: show message to user in WorkoutSession
@enduml