@startuml

abstract class Command

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class DietManager {

}

class DietSession {

}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml